config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 

  resources :battles
  resources :arenas
  resources :battle_pets
  resources :accounts
  devise_for :users
         
  namespace :v1, :defaults => { :format => :json } do 
     get :me, to: 'accounts#me'
     post :generate_pet, to: 'battle_pets#generate_pet'
     get :my_battle_pets, to: 'accounts#my_battle_pets'
     get :pet_leaderboard, to: 'battle_pets#leaderboard'
     
     get :my_battles, to: 'accounts#my_battles'
     get :my_battle_requests, to: 'accounts#my_battle_requests'
     get :leaderboard, to: 'accounts#leaderboard'

  	 resources :battles do
        put :accept
        put :deny
        post :battle_update
     end
	   
     resources :arenas do 
        get :battles
     end

     resources :battle_pets do
        get :battles
        get :train
        post :authed_get_pet_for_battle
        get :generate_training_pet
     end

     
     resources :accounts do
         get :battle_pets
         get :battles
     end
  end
end

app/models/battle_pet.rb
class BattlePet < ApplicationRecord
  belongs_to :account

  validates :status, presence: true, length: { maximum: 25 }, inclusion: { in: %w(active locked removed retired resting), message: "Status is not valid" }, allow_nil: false
  validates :strength, presence: true, numericality: { only_decimal: true }
  validates :agility, presence: true, numericality: { only_decimal: true }
  validates :wit, presence: true, numericality: { only_decimal: true }
  validates :speed, presence: true, numericality: { only_decimal: true }
  validates :wisdom, presence: true, numericality: { only_decimal: true }
  validates :intelligence, presence: true, numericality: { only_decimal: true }
  validates :magic, presence: true, numericality: { only_decimal: true }
  validates :chi, presence: true, numericality: { only_decimal: true }
  validates :healing_power, presence: true, numericality: { only_decimal: true }
  validates :experience, presence: true, numericality: { only_integer: true }

  def get_battles
    #TODO update model associations for many to many battles to pets
    battles_started = Battle.where(pet1_id:id)
    challenges = Battle.where(pet2_id:id)
    results = battles_started.present? && challenges.present? ? battles_started+challenges : (battles_started.present? ? battles_started : (challenges.present? ? challenges : Array.new))
  end

  def level_up

  	if experience >= level * BATTLE_PET_LEVEL_UP_EXPERIENCE
  		self.level += 1
  		self.strength += more_strength
      self.agility += more_agility
      self.wit += more_wit
      self.speed += more_speed
      self.wisdom += more_wisdom
      self.intelligence += more_intelligence
      self.magic += more_magic
      self.chi += more_chi
      self.healing_power += more_healing_power
  	end
  end

   def generate_training_battle_pet   
    BattlePet.new({name:"Mr. Battle Pet", status:'active', level:level, experience: ((level-1)*BATTLE_PET_LEVEL_UP_EXPERIENCE)+rand(1..(BATTLE_PET_LEVEL_UP_EXPERIENCE-1)),  strength: more_strength*level, agility: more_agility*level, wit: more_wit*level, speed: more_speed*level, wisdom: more_wisdom*level, intelligence: more_intelligence*level, magic: more_magic*level, chi: more_chi*level, healing_power: more_healing_power*level})    
  end

  def initialize_pet
    self.id=nil
    self.level=1
    self.status='active'
    self.retired=0
    self.experience=0
    self.auto_accept_play_for_points_requests=0
    self.won=0
    self.lost=0
    self.tied=0
    self.strength=more_strength
    self.agility=more_agility
    self.wit=more_wit
    self.speed=more_speed
    self.wisdom=more_wisdom
    self.intelligence=more_intelligence
    self.magic=more_magic
    self.chi=more_chi
    self.healing_power=more_healing_power
  end


  def pet_battle_exists auth
    #TODO update model associations for many to many battles to users
    battles_started = Battle.where(pet1_id:id, call_auth_code:auth)
    challenges = Battle.where(pet2_id:id, call_auth_code:auth)

    return battles_started.present? || challenges.present?
  end

  private

  def more_strength
    rand(5..10)
  end

  def more_agility
    rand(5..10)
  end

  def more_wit
    rand(5..10)
  end

  def more_speed
    rand(5..10)
  end

  def more_wisdom
    rand(1..5)
  end

  def more_intelligence
    rand(5..10)
  end

  def more_magic
    rand(1..5)
  end

  def more_chi
    rand(1..5)
  end

  def more_healing_power
    rand(1..5)
  end

end

app/controllers/battle_pets_controller.rb
class BattlePetsController < ApplicationController
  before_action :check_admin_permissions
  before_action :check_battle_pet, only: [:show, :edit, :update, :destroy]

  def index
    @battle_pets = BattlePet.all
  end

  def show
  end

  def new
    @battle_pet = BattlePet.new
  end

  def edit
  end

  def create
    @battle_pet = BattlePet.new(battle_pet_params)
    @battle_pet.updated_by = account_id
    @battle_pet.created_by = account_id
    @battle_pet.account = current_user.account
      
    respond_to do |format|
      if @battle_pet.save
        format.html { redirect_to @battle_pet, notice: 'Battle pet was successfully created.' }
        format.json { render :show, status: :created, location: @battle_pet }
      else
        format.html { render :new }
        format.json { render json: @battle_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    
    respond_to do |format|
      @battle_pet.updated_by = account_id
      
      if @battle_pet.update(battle_pet_params)
        format.html { redirect_to @battle_pet, notice: 'Battle pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @battle_pet }
      else
        format.html { render :edit }
        format.json { render json: @battle_pet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @battle_pet.destroy
    respond_to do |format|
      format.html { redirect_to battle_pets_url, notice: 'Battle pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_battle_pet
      @battle_pet = BattlePet.find_by_id(params[:id])
      return head(:not_found) unless @battle_pet.present?
    end

    def battle_pet_params
      params.require(:battle_pet).permit(:name, :about, :image, :level, :experience, :won, :lost, :tied, :town, :planet, :galaxy, :retired, :auto_accept_play_for_points_requests, :status, :account_id, :previous_owner_id, :original_owner_id, :strength, :agility, :wit, :speed, :wisdom, :intelligence, :magic, :chi, :healing_power, :status)
    end
end

app/controllers/v1/battle_pets_controller.rb
class V1::BattlePetsController < V1::V1Controller
  before_action :authenticate_user!, except: [:show, :index, :authed_get_pet_for_battle, :generate_training_pet, :leaderboard]
  before_action :check_admin_permissions, only: [:create]
  before_action only: [:show, :update] { |c| c.check_battle_pet params[:id] }
  before_action only: [:battles, :authed_get_pet_for_battle, :train, :generate_training_pet] { |c| c.check_battle_pet params[:battle_pet_id] }

  def index
    @battle_pets = BattlePet.where(retired:false)
    respond_with clean_public_json @battle_pets
  end

  def show
    respond_with clean_public_json @battle_pet
  end

  #Admin only create, users go through generate_pet
  def create

    @battle_pet = BattlePet.new(battle_pet_params)
    @battle_pet.account = current_user.account
    set_created_at_fields

    return head(:internal_server_error) unless @battle_pet.save

    respond_with @battle_pet
  end


  def update
    return head(:forbidden) unless @battle_pet.account_id == account_id
    
    @battle_pet.updated_by = account_id
    return head(:internal_server_error) unless @battle_pet.update(battle_pet_params)    

    respond_with @battle_pet
  end

  #Non restful endpoints

  def authed_get_pet_for_battle
    auth_code = params[:call_auth_code] if params[:call_auth_code].present? 
    return head(:forbidden) unless params[:call_auth_code].present? && @battle_pet.pet_battle_exists(auth_code)

    respond_with @battle_pet
  end

  # POST /battle_pets/generate_pet.json
  # name, about, image, town, planet, galaxy
  def generate_pet
    @battle_pet = BattlePet.new(user_battle_pet_params) 
    @battle_pet.account = current_user.account
    @battle_pet.initialize_pet    
    set_created_at_fields

    return head(:internal_server_error) unless @battle_pet.save
    
    respond_with @battle_pet
  end


  # GET /battle_pets/1/battles
  def battles
    respond_with clean_public_json (@battle_pet.get_battles)
  end

  def leaderboard
   @battle_pet = BattlePet.order(won: :desc, experience: :desc).take(100)
   respond_with clean_public_json @battle_pet
  end


 # GET /battle_pets/generate_random_pet.json
  def generate_training_pet
    new_battle_pet =  @battle_pet.generate_training_battle_pet

    respond_with new_battle_pet
  end


  #TODO update train to allow training in different arenas and with different battle games
  def train
    return head(:forbidden) unless @battle_pet.account_id == account_id
    
    battle = Battle.create_training_battle @battle_pet, 1
    
    return head(:bad_gateway) unless battle.send_battle_to_arena

    respond_with battle
  end

  #Helpers

  def clean_public_json response
    response.as_json( :except => [:strength, :agility, :wit, :speed, :wisdom, :intelligence, :magic, :chi, :healing_power] )
  end

  def check_battle_pet id
    @battle_pet = BattlePet.find_by_id(id)
    return head(:not_found) unless @battle_pet.present?
  end

  private

  def set_created_at_fields
    @battle_pet.updated_by = account_id
    @battle_pet.created_by = account_id
    @battle_pet.original_owner_id = account_id
    @battle_pet.account_id = account_id
  end

  def user_battle_pet_params
      params.permit(:name, :about, :image, :town, :planet, :galaxy, :retired, :auto_accept_play_for_points_requests)
    end 

    def battle_pet_params
      params.permit(:name, :about, :image, :level, :experience, :won, :lost, :tied, :town, :planet, :galaxy, :retired, :auto_accept_play_for_points_requests, :status, :account_id, :previous_owner_id, :original_owner_id, :strength, :agility, :wit, :speed, :wisdom, :intelligence, :magic, :chi, :healing_power, :status)
    end
end

app/helpers/battle_pets_helper.rb
module BattlePetsHelper
end

app/views/battle_pets/_form.html.erb
<%= form_for(battle_pet) do |f| %>
  <% if battle_pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(battle_pet.errors.count, "error") %> prohibited this battle_pet from being saved:</h2>

      <ul>
      <% battle_pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :about %>
    <%= f.text_field :about %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :level %>
    <%= f.number_field :level %>
  </div>

  <div class="field">
    <%= f.label :experience %>
    <%= f.number_field :experience %>
  </div>

  <div class="field">
    <%= f.label :won %>
    <%= f.number_field :won %>
  </div>

  <div class="field">
    <%= f.label :lost %>
    <%= f.number_field :lost %>
  </div>

  <div class="field">
    <%= f.label :tied %>
    <%= f.number_field :tied %>
  </div>

  <div class="field">
    <%= f.label :town %>
    <%= f.text_field :town %>
  </div>

  <div class="field">
    <%= f.label :planet %>
    <%= f.text_field :planet %>
  </div>

  <div class="field">
    <%= f.label :galaxy %>
    <%= f.text_field :galaxy %>
  </div>

  <div class="field">
    <%= f.label :retired %>
    <%= f.text_field :retired %>
  </div>

  <div class="field">
    <%= f.label :auto_accept_play_for_points_requests %>
    <%= f.text_field :auto_accept_play_for_points_requests %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  
  <div class="field">
    <%= f.label :account_id %>
    <%= f.number_field :account_id %>
  </div>

  <div class="field">
    <%= f.label :previous_owner_id %>
    <%= f.number_field :previous_owner_id %>
  </div>

  <div class="field">
    <%= f.label :original_owner_id %>
    <%= f.number_field :original_owner_id %>
  </div>

  <div class="field">
    <%= f.label :strength %>
    <%= f.number_field :strength %>
  </div>

  <div class="field">
    <%= f.label :agility %>
    <%= f.number_field :agility %>
  </div>

  <div class="field">
    <%= f.label :wit %>
    <%= f.number_field :wit %>
  </div>

  <div class="field">
    <%= f.label :speed %>
    <%= f.number_field :speed %>
  </div>

  <div class="field">
    <%= f.label :wisdom %>
    <%= f.number_field :wisdom %>
  </div>

  <div class="field">
    <%= f.label :intelligence %>
    <%= f.number_field :intelligence %>
  </div>

  <div class="field">
    <%= f.label :magic %>
    <%= f.number_field :magic %>
  </div>

  <div class="field">
    <%= f.label :chi %>
    <%= f.number_field :chi %>
  </div>

  <div class="field">
    <%= f.label :healing_power %>
    <%= f.number_field :healing_power %>
  </div>

 <div class="field">
    <%= f.label :created_at %>
    <%= f.date_field :created_at, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :updated_at %>
    <%= f.date_field :updated_at, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :updated_by %>
    <%= f.number_field :updated_by, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :created_by %>
    <%= f.number_field :created_by, :disabled=>true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/battle_pets/edit.html.erb
<h1>Editing Battle Pet</h1>

<%= render 'form', battle_pet: @battle_pet %>

<%= link_to 'Show', @battle_pet %> |
<%= link_to 'Back', battle_pets_path %>

app/views/battle_pets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Battle Pets</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>About</th>
      <th>Image</th>
      <th>Level</th>
      <th>Experience</th>
      <th>Won</th>
      <th>Lost</th>
      <th>Tied</th>
      <th>Town</th>
      <th>Planet</th>
      <th>Galaxy</th>
      <th>Retired</th>
      <th>Auto accept play for points requests</th>
      <th>Status</th>
      <th>Current owner</th>
      <th>Previous owner</th>
      <th>Original owner</th>
      <th>Strength</th>
      <th>Agility</th>
      <th>Wit</th>
      <th>Speed</th>
      <th>Wisdom</th>
      <th>Intelligence</th>
      <th>Magic</th>
      <th>Chi</th>
      <th>Healing power</th>
      <th>Updated by</th>
      <th>Created by</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @battle_pets.each do |battle_pet| %>
      <tr>
        <td><%= battle_pet.id %></td>
        <td><%= battle_pet.name %></td>
        <td><%= battle_pet.about %></td>
        <td><%= battle_pet.image %></td>
        <td><%= battle_pet.level %></td>
        <td><%= battle_pet.experience %></td>
        <td><%= battle_pet.won %></td>
        <td><%= battle_pet.lost %></td>
        <td><%= battle_pet.tied %></td>
        <td><%= battle_pet.town %></td>
        <td><%= battle_pet.planet %></td>
        <td><%= battle_pet.galaxy %></td>
        <td><%= battle_pet.retired %></td>
        <td><%= battle_pet.auto_accept_play_for_points_requests %></td>
        <td><%= battle_pet.status %></td>     
        <td><%= battle_pet.account_id %></td>
        <td><%= battle_pet.previous_owner_id %></td>
        <td><%= battle_pet.original_owner_id %></td>
        <td><%= battle_pet.strength %></td>
        <td><%= battle_pet.agility %></td>
        <td><%= battle_pet.wit %></td>
        <td><%= battle_pet.speed %></td>
        <td><%= battle_pet.wisdom %></td>
        <td><%= battle_pet.intelligence %></td>
        <td><%= battle_pet.magic %></td>
        <td><%= battle_pet.chi %></td>
        <td><%= battle_pet.healing_power %></td>
        <td><%= battle_pet.updated_by %></td>
        <td><%= battle_pet.created_by %></td>
        <td><%= link_to 'Show', battle_pet %></td>
        <td><%= link_to 'Edit', edit_battle_pet_path(battle_pet) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Battle Pet', new_battle_pet_path %>

app/views/battle_pets/new.html.erb
<h1>New Battle Pet</h1>

<%= render 'form', battle_pet: @battle_pet %>

<%= link_to 'Back', battle_pets_path %>

app/views/battle_pets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @battle_pet.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @battle_pet.name %>
</p>

<p>
  <strong>About:</strong>
  <%= @battle_pet.about %>
</p>

<p>
  <strong>Image:</strong>
  <%= @battle_pet.image %>
</p>

<p>
  <strong>Level:</strong>
  <%= @battle_pet.level %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @battle_pet.experience %>
</p>

<p>
  <strong>Won:</strong>
  <%= @battle_pet.won %>
</p>

<p>
  <strong>Lost:</strong>
  <%= @battle_pet.lost %>
</p>

<p>
  <strong>Tied:</strong>
  <%= @battle_pet.tied %>
</p>

<p>
  <strong>Town:</strong>
  <%= @battle_pet.town %>
</p>

<p>
  <strong>Planet:</strong>
  <%= @battle_pet.planet %>
</p>

<p>
  <strong>Galaxy:</strong>
  <%= @battle_pet.galaxy %>
</p>

<p>
  <strong>Retired:</strong>
  <%= @battle_pet.retired %>
</p>

<p>
  <strong>Auto accept play for points requests:</strong>
  <%= @battle_pet.auto_accept_play_for_points_requests %>
</p>

<p>
  <strong>Status:</strong>
  <%= @battle_pet.status %>
</p>

<p>
  <strong>Current owner:</strong>
  <%= @battle_pet.account_id %>
</p>

<p>
  <strong>Previous owner:</strong>
  <%= @battle_pet.previous_owner_id %>
</p>

<p>
  <strong>Original owner:</strong>
  <%= @battle_pet.original_owner_id %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @battle_pet.strength %>
</p>

<p>
  <strong>Agility:</strong>
  <%= @battle_pet.agility %>
</p>

<p>
  <strong>Wit:</strong>
  <%= @battle_pet.wit %>
</p>

<p>
  <strong>Speed:</strong>
  <%= @battle_pet.speed %>
</p>

<p>
  <strong>Wisdom:</strong>
  <%= @battle_pet.wisdom %>
</p>

<p>
  <strong>Intelligence:</strong>
  <%= @battle_pet.intelligence %>
</p>

<p>
  <strong>Magic:</strong>
  <%= @battle_pet.magic %>
</p>

<p>
  <strong>Chi:</strong>
  <%= @battle_pet.chi %>
</p>

<p>
  <strong>Healing power:</strong>
  <%= @battle_pet.healing_power %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @battle_pet.updated_at %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @battle_pet.updated_by %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @battle_pet.created_at %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @battle_pet.created_by %>
</p>

<%= link_to 'Edit', edit_battle_pet_path(@battle_pet) %> |
<%= link_to 'Back', battle_pets_path %>