config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 

  resources :battles
  resources :arenas
  resources :battle_pets
  resources :accounts
  devise_for :users
         
  namespace :v1, :defaults => { :format => :json } do 
     get :me, to: 'accounts#me'
     post :generate_pet, to: 'battle_pets#generate_pet'
     get :my_battle_pets, to: 'accounts#my_battle_pets'
     get :pet_leaderboard, to: 'battle_pets#leaderboard'
     
     get :my_battles, to: 'accounts#my_battles'
     get :my_battle_requests, to: 'accounts#my_battle_requests'
     get :leaderboard, to: 'accounts#leaderboard'

  	 resources :battles do
        put :accept
        put :deny
        post :battle_update
     end
	   
     resources :arenas do 
        get :battles
     end

     resources :battle_pets do
        get :battles
        get :train
        post :authed_get_pet_for_battle
        get :generate_training_pet
     end

     
     resources :accounts do
         get :battle_pets
         get :battles
     end
  end
end

app/models/arena.rb
class Arena < ApplicationRecord
      
	validates :name, presence: true, length: { maximum: 100 }
    validates :url, presence: true
    validates :port, presence: true, numericality: { only_integer: true }
  
    def self.get_arena_for_fight arena_id
	    if arena_id.present?
	    	arena = Arena.find_by_id(arena_id)
	    	return arena if arena.present? && arena.id > 0
	    end
	    return Arena.new({name:'Default Arena', description:"You don't have any arenas in your system.", url:DEFAULT_ARENA_V1_BATTLES_URL, port: DEFAULT_ARENA_PORT })
	 end
end

app/controllers/arenas_controller.rb
class ArenasController < ApplicationController
  before_action :check_admin_permissions
  before_action :check_arena, only: [:show, :edit, :update, :destroy]  
  
  def index
    @arenas = Arena.all
  end

  def show
  end

  def new
    @arena = Arena.new
  end

  def edit
  end

  def create
    
    @arena = Arena.new(arena_params)
    @arena.updated_by = account_id
    @arena.created_by = account_id

    respond_to do |format|
      if @arena.save
        format.html { redirect_to @arena, notice: 'Arena was successfully created.' }
        format.json { render :show, status: :created, location: @arena }
      else
        format.html { render :new }
        format.json { render json: @arena.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @arena.updated_by = account_id
      
      if @arena.update(arena_params)
        format.html { redirect_to @arena, notice: 'Arena was successfully updated.' }
        format.json { render :show, status: :ok, location: @arena }
      else
        format.html { render :edit }
        format.json { render json: @arena.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @arena.destroy
    respond_to do |format|
      format.html { redirect_to arenas_url, notice: 'Arena was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_arena
      @arena = Arena.find_by_id(params[:id])
      return head(:not_found) unless @arena.present?
    end

    def arena_params
      params.require(:arena).permit(:name, :description, :rated, :url, :port)
    end
end

app/controllers/v1/arenas_controller.rb
class V1::ArenasController < V1::V1Controller
  before_action :authenticate_user!
  before_action :check_admin_permissions, only: [:create, :update]  
  before_action :check_arena, only: [:show, :update] 

  def index
    @arenas = Arena.all
    respond_with @arenas
  end

  def show
    respond_with @arena
  end


  #Admin only RESTful create
  def create
    @arena = Arena.new(arena_params)
    @arena.updated_by = account_id
    @arena.created_by = account_id   

    return head(:internal_server_error) unless @arena.save

    respond_with @arena
  end


  #Admin only RESTful update
  def update
    @arena.updated_by = account_id

    return head(:internal_server_error) unless @arena.update(arena_params)

    respond_with @arena
  end

  private
    def check_arena
      @arena = Arena.find_by_id(params[:id])
      return head(:not_found) unless @arena.present?
    end

    def arena_params
      params.permit(:name, :description, :rated, :url, :port)
    end
end

app/helpers/arenas_helper.rb
module ArenasHelper
end

app/views/arenas/_form.html.erb
<%= form_for(arena) do |f| %>
  <% if arena.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arena.errors.count, "error") %> prohibited this arena from being saved:</h2>

      <ul>
      <% arena.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :rated %>
    <%= f.text_field :rated %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>


  <div class="field">
    <%= f.label :port %>
    <%= f.number_field :port %>
  </div>

  <div class="field">
    <%= f.label :created_at %>
    <%= f.date_field :created_at, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :updated_at %>
    <%= f.date_field :updated_at, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :updated_by %>
    <%= f.number_field :updated_by, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :created_by %>
    <%= f.number_field :created_by, :disabled=>true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/arenas/edit.html.erb
<h1>Editing Arena</h1>

<%= render 'form', arena: @arena %>

<%= link_to 'Show', @arena %> |
<%= link_to 'Back', arenas_path %>

app/views/arenas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Arenas</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Rated</th>
      <th>Url</th>
      <th>Port</th>
      <th>Updated by</th>
      <th>Created by</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @arenas.each do |arena| %>
      <tr>
        <td><%= arena.id %></td>
        <td><%= arena.name %></td>
        <td><%= arena.description %></td>
        <td><%= arena.rated %></td>
        <td><%= arena.url %></td>
        <td><%= arena.port %></td>
        <td><%= arena.updated_by %></td>
        <td><%= arena.created_by %></td>
        <td><%= link_to 'Show', arena %></td>
        <td><%= link_to 'Edit', edit_arena_path(arena) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Arena', new_arena_path %>

app/views/arenas/new.html.erb
<h1>New Arena</h1>

<%= render 'form', arena: @arena %>

<%= link_to 'Back', arenas_path %>

app/views/arenas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @arena.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @arena.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @arena.description %>
</p>

<p>
  <strong>Rated:</strong>
  <%= @arena.rated %>
</p>

<p>
  <strong>Url:</strong>
  <%= @arena.url %>
</p>

<p>
  <strong>Url:</strong>
  <%= @arena.port  %>
</p>
<p>
  <strong>Updated at:</strong>
  <%= @arena.updated_at %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @arena.updated_by %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @arena.created_at %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @arena.created_by %>
</p>

<%= link_to 'Edit', edit_arena_path(@arena) %> |
<%= link_to 'Back', arenas_path %>