config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index' 

  resources :battles
  resources :arenas
  resources :battle_pets
  resources :accounts
  devise_for :users
         
  namespace :v1, :defaults => { :format => :json } do 
     get :me, to: 'accounts#me'
     post :generate_pet, to: 'battle_pets#generate_pet'
     get :my_battle_pets, to: 'accounts#my_battle_pets'
     get :pet_leaderboard, to: 'battle_pets#leaderboard'
     
     get :my_battles, to: 'accounts#my_battles'
     get :my_battle_requests, to: 'accounts#my_battle_requests'
     get :leaderboard, to: 'accounts#leaderboard'

  	 resources :battles do
        put :accept
        put :deny
        post :battle_update
     end
	   
     resources :arenas do 
        get :battles
     end

     resources :battle_pets do
        get :battles
        get :train
        post :authed_get_pet_for_battle
        get :generate_training_pet
     end

     
     resources :accounts do
         get :battle_pets
         get :battles
     end
  end
end

app/models/battle.rb
require "net/http"
require "uri"

class Battle < ApplicationRecord
	validates :name, presence: true, length: { maximum: 100 }
  	validates :user1_id, presence: true, numericality: { only_integer: true }
  	validates :user2_id, presence: true, numericality: { only_integer: true }
  	validates :pet1_id, presence: true, numericality: { only_integer: true }
  	validates :pet2_id, presence: true, numericality: { only_integer: true }
  	validates :status, presence: true, length: { maximum: 25 }, inclusion: { in: %w(auto-accepted battled invited accepted legendary denied), message: "Status is not valid" }, allow_nil: false

	def send_battle_to_arena	 		
		self.save unless id.present?

		arena = Arena.get_arena_for_fight arena_id
		uri = URI.parse(arena.url + '/v1/battles/' + id.to_s + '/fight')	
		port = arena.port

		http = Net::HTTP.new(uri.host, port)
		if USE_SSL
	    	http.use_ssl = true
			http.verify_mode = OpenSSL::SSL::VERIFY_NONE # Sets the HTTPS verify mode
		end
		request = Net::HTTP::Post.new(uri.request_uri)
		request.set_form_data(self.as_json)

		begin
			response = http.request(request)
			puts 'SENT ARENA BATTLE REQUEST : response =>' + response.inspect
			true
		rescue
			puts 'FAILED ARENA BATTLE REQUEST : response =>' + response.inspect			
			false
		end		
	 end

	 #TODO break this up so the specific models update themselves, after tests in for battle model
	def process_battle_results
		self.status = "legendary"

		if self.is_tie
			user1 = Account.find_by_id(user1_id)
			if(user1.present?)
				user1.tied = user1.tied + 1
				user1.save
			end

			user2 = Account.find_by_id(user2_id)
			if(user2.present?)
				user2.tied = user2.tied + 1
				user2.save
			end
			return
		end

		is_training = pet2_id == -1

		#training may not have real users or pets or a pet may disappear by the time the battle is over		
		#TODO Move these to theirs respective models
		winner = Account.find_by_id(winning_user_id.present? ? winning_user_id : -1)		
		if(winner.present?)
			
			winner.won = winner.won + 1 unless is_training
			winner.experience = winner.experience + (winner_experience.present?  ? winner_experience :  0)
			winner.gold = winner.gold + (winner_gold.present? ? winner_gold :  0)
			winner.level_up
			winner.save
		end

		winning_pet = BattlePet.find_by_id(winning_pet_id.present? ? winning_pet_id : -1)	
		if(winning_pet.present?)
			winning_pet.won = winning_pet.won + 1 unless is_training
			winning_pet.experience = winning_pet.experience + (winner_experience.present? ? winner_experience : 0)
			winning_pet.level_up
			winning_pet.save
		end

		loser = Account.find_by_id(user1_id != winning_user_id ? user1_id : user2_id)
		if(loser.present?)
			
			loser.lost = loser.lost + 1 unless is_training
			loser.experience = loser.experience + (loser_experience.present?  ? loser_experience :  0)
			loser.level_up
			loser.save
		end

		losing_pet = BattlePet.find_by_id(pet1_id != winning_pet_id ? pet1_id : pet2_id)
		if(losing_pet.present?)

			losing_pet.lost = losing_pet.lost + 1 unless is_training
			losing_pet.experience = losing_pet.experience + (loser_experience.present? ? loser_experience : 0)
			losing_pet.level_up

			if play_for_keeps && winner.present? && winner.id >= 0
				losing_pet.previous_owner_id = losing_pet.account_id
  				losing_pet.account_id = winner.id
			end  

			losing_pet.save
		end

		self.call_auth_code = nil # don't let it be used again for pet data lookups or battle responses
		self.save

  	end

	def update_battle_from_response data

	    self.winning_user_id = data[:winning_user_id]
	    self.winning_pet_id = data[:winning_pet_id]
	    self.winner_gold = data[:winner_gold]
	    self.winner_experience = data[:winner_experience]
	    self.loser_experience = data[:loser_experience]
	    self.is_tie = data[:is_tie]
	    self.status = data[:status]
	    self.battled_on = data[:battled_on]
	    self.score  = data[:score]
		self.save
	end

	def self.create_training_battle battle_pet, arena_id
		battle = Battle.new
	    battle.name = "Training"
	    battle.call_auth_code = SecureRandom.uuid
	    battle.arena_id = arena_id
	    battle.user1_id = battle_pet.account_id
	    battle.user2_id = -1
	    battle.pet1_id = battle_pet.id
	    battle.pet2_id = -1
	    battle.battle_game_id = 1
	    battle.status = "accepted"
	    battle.updated_by = battle_pet.account_id
	    battle.created_by = battle_pet.account_id
	    battle.save
	    battle
	end

end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  before_action :check_admin_permissions
  before_action :check_battle, only: [:show, :edit, :update, :destroy]

  def index
    @battles = Battle.all
  end

  def show
  end

  def new
    @battle = Battle.new
  end

  def edit
  end

  def create
    @battle = Battle.new(battle_params)
    @battle.call_auth_code = SecureRandom.uuid
    @battle.updated_by = account_id
    @battle.created_by = account_id

    respond_to do |format|
      if @battle.save
        format.html { redirect_to @battle, notice: 'Battle was successfully created.' }
        format.json { render :show, status: :created, location: @battle }
      else
        format.html { render :new }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @battle.updated_by = account_id
    
      if @battle.update(battle_params)
        format.html { redirect_to @battle, notice: 'Battle was successfully updated.' }
        format.json { render :show, status: :ok, location: @battle }
      else
        format.html { render :edit }
        format.json { render json: @battle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @battle.destroy
    respond_to do |format|
      format.html { redirect_to battles_url, notice: 'Battle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_battle
      @battle = Battle.find_by_id(params[:id])
      return head(:not_found) unless @battle.present?
    end

    def battle_params
      params.require(:battle).permit(:name, :user1_id, :user2_id, :arena_id, :pet1_id, :pet2_id, :play_for_keeps, :battle_game_id, :status)
    end
end

app/controllers/v1/battles_controller.rb
class V1::BattlesController < V1::V1Controller
  before_action :authenticate_user!, except: [:battle_update]
  before_action only: [:accept, :deny] { |c| c.check_responder_permissions params[:battle_id] }
  before_action only: [:invite, :accept, :deny] { |c| c.check_battle params[:battle_id] }
  before_action only: [:update] { |c| c.check_owner_permissions params[:id] }
  before_action only: [:show, :update] { |c| c.check_battle params[:id] }

  def index
    @battles = Battle.all
    respond_with @battles
  end

  def show
    respond_with @battle
  end

# PUT /battles/1/accept
  def accept
    return head(:bad_request) unless @battle.status == "invited"
    
    @battle.status = "accepted"
    @battle.updated_by = account_id 
    return head(:internal_server_error) unless  @battle.save

    return head(:bad_gateway) unless @battle.send_battle_to_arena
   
    respond_with @battle
  end  

  def create
    
    @battle = Battle.new(battle_params)
    
    pet = BattlePet.find_by_id(@battle.pet2_id)
    return head(:forbidden) unless @battle.user1_id == account_id && @battle.user2_id != account_id
    return head(:not_found) unless pet.present? && !pet.retired
    

    @battle.call_auth_code = SecureRandom.uuid
    @battle.updated_by = account_id 
    @battle.created_by = account_id 
 
    if (!@battle.play_for_keeps.present? || !@battle.play_for_keeps) && (pet.auto_accept_play_for_points_requests.present? && pet.auto_accept_play_for_points_requests)
      @battle.status = "auto-accepted"
      return head(:internal_server_error) unless @battle.save      
      @battle.send_battle_to_arena and return
    end

    @battle.status = "invited"
    return head(:internal_server_error) unless @battle.save 

    respond_with @battle
  end

  def update
    @battle.updated_by = account_id 

    return head(:internal_server_error) unless  @battle.update(battle_params)

    respond_with @battle
  end


  #Non restful endpoints
  #endpoint called by arenas to give battle completion update
  # PUT /battles/1/battle_update
  def battle_update
    puts "WELCOME BACK !!!!"
    update_values = params.permit(:id, :battled_on, :winning_user_id, :winning_pet_id, :is_tie, :status, :original_id, :score, :call_auth_code, :winner_experience, :loser_experience, :winner_gold)
    
    original_battle = Battle.find_by_id(update_values[:original_id])

    return head(:forbidden) unless update_values['call_auth_code'] == original_battle.call_auth_code

    original_battle.update_battle_from_response update_values
    
    original_battle.process_battle_results 

    head(:ok)
  end

# PUT /battles/1/deny
  def deny
      return head(:bad_request) unless @battle.status == "invited"
    
    @battle.status = "denied"
    @battle.updated_by = account_id 
    return head(:internal_server_error) unless  @battle.save

    respond_with @battle
  end

  #Helpers

  def check_owner_permissions id
      battle = Battle.find_by_id(id)
      return head(:forbidden) unless battle.present? && battle.created_by == account_id   
    end


    def check_responder_permissions id
      battle = Battle.find_by_id(id)
      return head(:forbidden) unless battle.present? && battle.user2_id == account_id    
    end

    def check_battle id
      @battle = Battle.find_by_id(id)
      return head(:not_found) unless @battle.present? 
    end

  private

    def battle_params
      params.permit(:name, :user1_id, :user2_id, :arena_id, :pet1_id, :pet2_id, :play_for_keeps, :battle_game_id, :status)
    end
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/battles/_form.html.erb
<%= form_for(battle) do |f| %>
  <% if battle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(battle.errors.count, "error") %> prohibited this battle from being saved:</h2>

      <ul>
      <% battle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :call_auth_code %>
    <%= f.text_field :call_auth_code, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :arena_id %>
    <%= f.number_field :arena_id %>
  </div>

  <div class="field">
    <%= f.label :pet1_id %>
    <%= f.number_field :pet1_id %>
  </div>

  <div class="field">
    <%= f.label :pet2_id %>
    <%= f.number_field :pet2_id %>
  </div>

  <div class="field">
    <%= f.label :battled_on %>
    <%= f.datetime_select :battled_on %>
  </div>

  <div class="field">
    <%= f.label :winning_user_id %>
    <%= f.number_field :winning_user_id %>
  </div>

  <div class="field">
    <%= f.label :winning_pet_id %>
    <%= f.number_field :winning_pet_id %>
  </div>

  <div class="field">
    <%= f.label :battle_game_id %>
    <%= f.number_field :battle_game_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

<div class="field">
    <%= f.label :play_for_keeps %>
    <%= f.text_field :play_for_keeps %>
  </div>

 <div class="field">
    <%= f.label :created_at %>
    <%= f.date_field :created_at, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :updated_at %>
    <%= f.date_field :updated_at, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :updated_by %>
    <%= f.number_field :updated_by, :disabled=>true %>
  </div>

  <div class="field">
    <%= f.label :created_by %>
    <%= f.number_field :created_by, :disabled=>true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/battles/edit.html.erb
<h1>Editing Battle</h1>

<%= render 'form', battle: @battle %>

<%= link_to 'Show', @battle %> |
<%= link_to 'Back', battles_path %>

app/views/battles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Battles</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Arena</th>
      <th>Name</th>
      <th>Pet1</th>
      <th>Pet2</th>
      <th>Battled on</th>
      <th>Winning User Id</th>
      <th>Winning Pet Id</th>
      <th>Battle game</th>
      <th>Status</th>
      <th>Play for keeps</th>
      <th>Winner XP</th>
      <th>Loser XP</th>
      <th>Winner Gold</th>
      <th>Updated by</th>
      <th>Created by</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @battles.each do |battle| %>
      <tr>
        <td><%= battle.id %></td>
        <td><%= battle.name %></td>
        <td><%= battle.arena_id %></td>
        <td><%= battle.pet1_id %></td>
        <td><%= battle.pet2_id %></td>
        <td><%= battle.battled_on %></td>
        <td><%= battle.winning_user_id %></td>
        <td><%= battle.winning_pet_id %></td>
        <td><%= battle.battle_game_id %></td>
        <td><%= battle.status %></td>
        <td><%= battle.play_for_keeps %></td>
        <td><%= battle.winner_experience %></td>
        <td><%= battle.loser_experience %></td>
        <td><%= battle.winner_gold %></td>
        <td><%= battle.updated_by %></td>
        <td><%= battle.created_by %></td>
        <td><%= link_to 'Show', battle %></td>
        <td><%= link_to 'Edit', edit_battle_path(battle) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Battle', new_battle_path %>

app/views/battles/new.html.erb
<h1>New Battle</h1>

<%= render 'form', battle: @battle %>

<%= link_to 'Back', battles_path %>

app/views/battles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @battle.id %>
</p>

<p>
  <strong>Arena:</strong>
  <%= @battle.arena_id %>
</p>

<p>
  <strong>Pet1:</strong>
  <%= @battle.pet1_id %>
</p>

<p>
  <strong>Pet2:</strong>
  <%= @battle.pet2_id %>
</p>

<p>
  <strong>Battled on:</strong>
  <%= @battle.battled_on %>
</p>

<p>
  <strong>Winning User Id:</strong>
  <%= @battle.winning_user_id %>
</p>

<p>
  <strong>Winning Pet Id:</strong>
  <%= @battle.winning_pet_id %>
</p>

<p>
  <strong>Battle game:</strong>
  <%= @battle.battle_game_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @battle.status %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @battle.updated_at %>
</p>


<p>
  <strong>Status:</strong>
  <%= @battle.status %>
</p>


<p>
  <strong>Play for Keeps:</strong>
  <%= @battle.play_for_keeps %>
</p>


<p>
  <strong>Winner XP:</strong>
  <%= @battle.winner_experience %>
</p>


<p>
  <strong>Loser XP:</strong>
  <%= @battle.winner_experience %>
</p>

<p>
  <strong>Winner Gold:</strong>
  <%= @battle.winner_gold %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @battle.created_at %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @battle.created_by %>
</p>

<%= link_to 'Edit', edit_battle_path(@battle) %> |
<%= link_to 'Back', battles_path %>